trunk/Catpic.Host/Areas/Portal/Controllers/DownloadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Catpic.Host.Areas.Portal.Controllers
{
    public class DownloadController : Controller
    {
        //
        // GET: /Portal/Download/

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult SourceCode()
        {
            return View();
        }
    }
}

trunk/Catpic.Host/Areas/Portal/Controllers/GadgetServerController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Async;
using Catpic.Gadgets;
using Catpic.Gadgets.Security;
using Catpic.Host.Engine.Inline;
using Catpic.Host.Engine.Security;

namespace Catpic.Host.Areas.Portal.Controllers
{
    /// <summary>
    /// Controller of demo page which shows gadget server capabilities
    /// </summary>
    public class GadgetServerController : AsyncController
    {
        public const string DefaultGadget = "http://www.rareworksllc.com/moonphases/LunarPhaseGadget.xml";

        private readonly IRequestHandler _handler;
        private readonly InlineContextFactory _inlineFactory;
        //
        // GET: /Portal/Demo/

        public GadgetServerController(IRequestHandler handler, InlineContextFactory inlineFactory)
        {
            _handler = handler;
            _inlineFactory = inlineFactory;
        }

        public ActionResult Index()
        {
            ViewData["url"] = DefaultGadget;
            ViewData["token"] = SecurityTokenHelper.GetToken(User);
            return View();
        }

        [HttpPost]
        public ActionResult Container(string url)
        {
            ViewData["url"] = url;
            ViewData["token"] = SecurityTokenHelper.GetToken(User);
            return View();
        }

        [HttpGet]
        public ActionResult Container()
        {
            ViewData["url"] = DefaultGadget;
            ViewData["token"] = SecurityTokenHelper.GetToken(User);
            return View();
        }

        public ActionResult Inline()
        {
            return View();
        }

        public void RenderInlineAsync(string url, string mode)
        {
            //emulate query string
            NameValueCollection query = new NameValueCollection();
            query.Add("url", url);
            query.Add("renderType", mode);

            //emulate response output
            StringWriter writer = new StringWriter();

            var context = _inlineFactory.Create(query, writer,ControllerContext.HttpContext);
            AsyncManager.OutstandingOperations.Increment();
            _handler.CreateGadgetAsync(context)
                .ContinueWith(t =>
                {
                    AsyncManager.Parameters["content"] = writer.ToString();
                    AsyncManager.OutstandingOperations.Decrement();
                });
        }

        public ActionResult RenderInlineCompleted(string content)
        {
            return Content(content);
        }
    }
}

trunk/Catpic.Host/Areas/Portal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Catpic.Host.Areas.Portal.Controllers
{
    /// <summary>
    /// Home page contoller
    /// </summary>
    public class HomeController : Controller
    {
        //
        // GET: /Portal/Home/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }


        public ActionResult Resources()
        {
            return View();
        }

    }
}

trunk/Catpic.Host/Areas/Portal/Views/Home/Details.cshtml
@{
    ViewBag.Title = "Catpic Details";
    Layout = "~/Areas/Portal/Views/Shared/_Layout.cshtml";
}
<div class="homepage-hero-small">
	<h1>
		<span>Scalable.</span> 
		<span>Open.</span> 
		<span>Extensible.</span>
	</h1>
</div>
<p class="sub-hero-message"><b>Catpic</b> is an open source <i>.NET</i> project which implements OpenSocial container and provides ability to use <i>Google gadgets</i> -  simple HTML and JavaScript applications that can be embedded in webpages and other apps.  Gadgets are developed by Google and third-party developers using the Google Gadgets API and basic web technologies such as XML, JavaScript, Flash.
    This site is just demo: <b>Catpic</b> is distributed as <i>.NET assemblies</i> and resource files (javascript API and server configuration files). It provides:
</p>
<div style="padding-left:20px">
    <ul class="arrow-bullets">
        <li>opensocial container specification 1.1(2.0) implementation (in progress)</li>
        <li>implementation of google gadgets specification (done partially)</li>
        <li>ability to process platform-independed components - gadgets</li>
        <li>fully <i>.NET</i> implementation on server side</li>
        <li>extensibility by custom modules</li>
        <li>simple integration into existing <i>ASP.NET</i>/ <i>ASP.NET MVC</i> application via <a href="http://nuget.org">NuGet</a> package</li>
    </ul>
</div>

trunk/Catpic.Host/Areas/Portal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Catpic Home";
    Layout = "~/Areas/Portal/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script>
        function GoTo(url) {
            parent.location = url;
        }
    </script>
}
<div class="homepage-hero">
	<h1>
		<span>Scalable.</span> 
		<span>Open.</span> 
		<span>Extensible.</span>
	</h1>
    <p>Gadget server</p>
	<p>OpenSocial container</p>
	<p>written on .NET</p>
	<div class="homepage-feature-boxes">
		<div class="col2" onclick="GoTo('@Url.Action("Index", "Download", new { area = "Portal" })');">
			<h2>download</h2>
			<a href="#">use now</a>
		</div>
		<div class="col3" onclick="GoTo('@Url.Action("Details", "Home", new { area = "Portal" })');">
			<h2>details</h2>
			<a href="#">learn now</a>
		</div>
		<div class="col1" onclick="GoTo('@Url.Action("Index", "GadgetServer", new { area = "Portal" })');">
			<h2>gadget</h2>
            <a href="#">try now</a>
		</div>
	</div>
</div>
<div class="home-infobox vwo_loaded">
    <b>Catpic</b> is <i>OpenSocial Container</i> for .NET developers that provides extensible <i>component hosting environment</i> and <i>social facilities</i> to existing  .NET applications using best practices.
</div>

trunk/Catpic.Host/Areas/Portal/Views/Home/Resources.cshtml
@{
    ViewBag.Title = "Useful Resources";
    Layout = "~/Areas/Portal/Views/Shared/_Layout.cshtml";
}
@*<ul>
    <li><a href="http://catpic.codeplex.com">Project repository</a></li>
    <li><a href="http://shindig.apache.org/">Apache Shindig</a></li>
    <li><a href="https://developers.google.com/gadgets/docs/dev_guide">gadgets.* API Developer's Guide</a></li>
    <li><a href="http://www.google.com/ig/directory?synd=open ">iGoogle gadget catalog</a></li>
</ul>
*@


<div id="content" class="textpage">
   <h2>useful resources</h2>
    <div class="content-blocks">
       <div class="col">
            <a href="http://opensocial.org" class="blue-box" onclick="">
                <span>opensocial<br>standard</span>
            </a>
            <div>
                <a href="http://docs.opensocial.org/display/OSD/Specs">OpenSocial specs</a>
            </div>
            <p>
               Friends are fun, but they're only on some websites. OpenSocial helps these sites share their social data with the web. Applications that use the OpenSocial APIs can be embedded within a social network itself, or access a site's social data from anywhere on the web
            </p>
            <span>
                <a href="http://opensocial.org" title="Forums" class="site-arrowlink1">Visit Site</a>
            </span>
        </div>
        <div class="col">
            <a href="http://shindig.apache.org/" class="green-box" onclick="">
                <span>apache<br/>shindig</span>
            </a>
            <div>
                <a href="http://shindig.apache.org/community/index.html">Community help</a>
            </div>
            <p>
                Apache Shindig is an OpenSocial container and helps you to start hosting OpenSocial apps quickly by providing the code to render gadgets, proxy requests, and handle REST and RPC requests.
            </p>
            <span>
                <a href="http://shindig.apache.org/" title="Forums" class="site-arrowlink1">Visit Site</a>
            </span>
        </div>
         <div class="col">
            <a href="https://developers.google.com/gadgets/docs/dev_guide" class="pink-box" onclick="">
                <span>gadget<br>api</span>
            </a>
            <div>
                <a href="https://developers.google.com/gadgets/docs/dev_guide">Developer's API</a>
            </div>
            <p>
                Gadgets are mini-applications built using HTML, with JavaScript, Flash or Silverlight for dynamic behaviors. Since gadgets can run on multiple sites and platforms, there are special tags and libraries that work in different places.
            </p>
            <span>
                <a href="https://developers.google.com/gadgets/docs/dev_guide" title="Forums" class="site-arrowlink1">View Docs</a>
            </span>
        </div>
         <div class="col">
            <a href="http://catpic.codeplex.com" class="blue-box" onclick="">
                <span>project<br/> repository</span>
            </a>
            <div>
                <a href="#">Contribute</a>
            </div>
            <p>
                Official project repository. You can find the latest releases, documentation, report issues, etc.
            </p>
            <span>
                <a href="http://catpic.codeplex.com/SourceControl/list/changesets" title="Source code" class="site-arrowlink1">Download sources</a>
                <a href="http://catpic.codeplex.com/workitem/list/basic" title="Issues" class="site-arrowlink1">Report issue</a>
                <a href="http://catpic.codeplex.com/documentation" title="Docs" class="site-arrowlink1">See docs</a>
            </span>
          </div>
    </div>
   <div id="disqus_thread"></div>
</div>